# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=140)),
                ("number", models.PositiveIntegerField()),
                ("detail", models.CharField(default=None, max_length=80)),
                ("zip_code", models.CharField(max_length=8)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=2)),
                ("country", models.CharField(max_length=30)),
            ],
        ),
    ]
