# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM ANDAMENTO", "On Going"),
                            ("ENTREGUE", "Delivered"),
                            ("PEDIDO REALIZADO", "Default"),
                        ],
                        default="PEDIDO REALIZADO",
                        max_length=30,
                    ),
                ),
                ("bought_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
