# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="sold_products", to="products.product"
            ),
        ),
    ]
