# Generated by Django 4.1.7 on 2023-03-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sold_by",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
