# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.PositiveIntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Eletrodomésticos", "Eletronics"),
                            ("Roupas", "Clothings"),
                            ("Celulares", "Smartphones"),
                            ("Casa", "Home"),
                            ("Informática", "It"),
                            ("Não informado", "Default"),
                        ],
                        default="Não informado",
                        max_length=50,
                    ),
                ),
                (
                    "thumbnail",
                    models.URLField(
                        default="https://www2.camara.leg.br/atividade-legislativa/comissoes/comissoes-permanentes/cindra/imagens/sem.jpg.gif"
                    ),
                ),
            ],
        ),
    ]
